import os
import glob
import pandas as pd
from snakemake.utils import min_version

min_version('7.16.0')

configfile: '../config/loniqbc.yaml'

#CFFE Lanes
LANES = ['CFFE_group1', 'CFFE_group2', 'CFFE_group3']

#Path to resource files
RESOURCES = os.path.abspath(config['resources'])

#Input files
CFFE_FASTA_DIR = f"{RESOURCES}/CFFE_fastas"

#Output files
LOG_DIR = config['log_prefix']
DEMUX_DIR = f"config['results']/demux_out"
IPYRAD_DIR= f"{config['results_prefix']}/ipyrad_out"
ADMIX_DIR = f"{config['results_prefix']}/admix_out"
PLINK_DIR = f"{config['results_prefix']}/plink_out"
MODEL_DIR = f"{config['results_prefix']}/model_out"
FIGURES_DIR = f"{config['results_prefix']}/figures"

rule all: 
    input:
        f'{DEMUX_DIR}/demux.done',
        f'{IPYRAD_DIR}/ipyrad.done',
        f'{ADMIX_DIR}/admix.done',
        f'{PLINK_DIR}/plink.done',
        f'{MODEL_DIR}/model.done',
        f'{FIGURES_DIR}/figures.done'

include: 'rules/ipyrad.smk'
include: 'rules/plink.smk'
include: 'rules/admix.smk'
include: 'rules/model.smk'

wildcard_constraints:
    lanes = '|'.join(LANES),
    